service: aws-bw-speaksentence
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DYNAMODB_SPEAKSENTENCE_TABLE: ${self:service}-speaksentence-${sls:stage}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:Scan*'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-speaksentence-${sls:stage}

functions:
  buildSpeakSentence:
    handler: handler.buildSpeakSentence
    events:
     - http:
         path: speakSentenceBXML
         method: get

  updateSpeakSentence:
    handler: handler.updateSpeakSentence
    events:
     - http:
         path: speakSentence
         method: post


resources:
  Resources:
    SpeakSentenceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-speaksentence-${sls:stage}
